platform :ios, ‘9.0’
#忽略第三方警告，注意
inhibit_all_warnings!
# Uncomment this line if you're using Swift or would like to use dynamic frameworks
use_frameworks!

target 'GBTaiJie' do
    pod 'AFNetworking’, ‘~> 3.0’
    pod 'SDWebImage'
    pod 'Masonry'
    pod 'MJRefresh'
    pod 'MBProgressHUD'
    pod 'MJExtension'
    # 启动页
    pod 'XHLaunchAd'
    # 滑动标签
    pod 'WMPageController'
    # 自定义导航栏
    pod 'WRNavigationBar','~>1.2.0’
    # 轮播图
    pod 'SDCycleScrollView', '~> 1.75'
    # 高度缓存
    pod 'UITableView+FDTemplateLayoutCell'
    # 空数据占位图
    pod 'DZNEmptyDataSet'
    # 小红点
    pod 'RKNotificationHub'
    # menu菜单
    pod 'GMenuController'
    # 下拉功能菜单
    pod 'YCXMenu'
    # 键盘控制器
    pod 'IQKeyboardManager'
    # 函数响应式框架
    pod 'ReactiveObjC'
    # textView占位
    pod 'ZWPlaceHolder'
    # 特色对话框
    pod 'SCLAlertView-Objective-C'
    # 扇形按钮菜单
    pod 'DCPathButton'
    # GIF图加载
    pod 'UIImageView-PlayGIF'
    # 相册图片选择器
    pod 'TZImagePickerController'
    # 图片浏览器
    pod 'YBImageBrowser'
    # 搜索
    pod 'PYSearch'
    # 星星✨
    pod 'HCSStarRatingView', '~> 1.5'
    # 七牛
    pod 'Qiniu'
    # 崩溃容错
    pod 'AvoidCrash'
    
    # 第三方sdk
    
    # 极光推送
    pod 'JPush'
    # 极光IM
    pod 'JMessage'
    # 极光统计
    pod 'JAnalytics'
    # 极光分享
    pod 'JShare'
    # 极光消息UI
#    pod 'AuroraIMUI'
#    pod 'YHPhotoKit'
#    pod 'RxSwift'
#    pod 'RxCocoa'
#    pod 'YHPopupView'
#    pod 'YHPhotoKit'
#    pod 'FMDB', '~> 2.6.2'
#    pod 'BaiduMapKit', '~> 3.3.2'
#    pod 'MessageDisplayKit'
end
